### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [kukuruza/CADillac#1]
Hello, under what license is this project released under ? Thank-you.

**Comment by kukuruza** [comment]
Hi there, the project is under Apache 2 (I added the license to the code.)

The dataset of ~1000 3D car models will be available at https://cmu.box.com/s/541gvrb7x4xkph8vi8xl15uqi8engfys (give it a try tomorrow, it is being uploaded at the moment). It consists of CAD models in the `.blend` format downloaded from 3DWarehouse website, cleaned, and annotated. I have the permission from 3DWarehouse for the non-commercial use of the models.

I will clean the code within a few weeks, add the examples, and upload the dataset of rendered images.
